version: "3.3"

services:
  fastapi-server:
    build:
      context: ${PWD}
      dockerfile: docker/inference.Dockerfile
    image: fastapi-server-cars:0.1.0
    ports:
      - "4000:4000"
    entrypoint:
      [
        "uvicorn",
        "src.api.fastapi:app",
        "--host",
        "0.0.0.0",
        "--port",
        "4000"
      ]
