---
# Settings set for inference
training:
  train_df_path: "data/annotations/train_df.csv"
  custom_crop: False
  model_name: "resnet101" # [resnet101 and resnet50]
  batch_size: 35
  epochs: 50

inference:
  run_inference: "True" # Needs to be changed to false when training, ensures that pretrained weights are not loaded during inference
  model_path: "models/resnet101_77.47_nocrop.pth" # Ensure that training.model_name supports model
